In [1]:
import torch

In [5]:
randint=torch.randint(-100, 100, (6,))
print(randint)

tensor([-70,  -3, -77, -12,  78, -20])


In [8]:
tensor= torch.tensor([[0.1,1.2],[2.2,3.3],[4.4,5.5]])
print(tensor)

tensor([[0.1000, 1.2000],
        [2.2000, 3.3000],
        [4.4000, 5.5000]])


In [10]:
zeros=torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
ones=torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
input= torch.empty(2,3)
input# these are either very large or small numbers

tensor([[1.5236e+00, 1.2345e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [17]:
arange=torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [20]:
linspace=torch.linspace(3,10,steps=5)
linspace# We have 5 differnt ones over 5 steps . adding the same amouunt in each iteration from 3 to 10. the increment are adjusted by pyt itself

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [24]:
logspace=torch.logspace(start=-10, end=10, steps=5)
logspace #increments in exponents/log

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [25]:
eye=torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [26]:
import numpy

In [27]:
numpy.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
a=torch.empty((2,3),dtype=torch.int64)
empty_like=torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [30]:
device= 'cuda' if torch.cuda.is_available() else 'cpu'

In [35]:
import time
 
start_time=time.time()

zeros=torch.zeros(1,1)
end_time=time.time()
elapsed_time=end_time-start_time

print(f"Elapsed Time: {elapsed_time:.4f}")

Elapsed Time: 0.0000


In [36]:
#%%time - time it takes to execute a block

In [40]:
probabilities=torch.tensor([0.1,0.9])#THey have to add up to 1
samples=torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples) #Checking the probability of happening

tensor([0, 1, 1, 1, 1, 1, 1, 0, 1, 0])


In [49]:
tensor=torch.tensor([1,2,3,4])
out=torch.cat((tensor,torch.tensor([5,6])),dim=0)
out# Concatenates the tensors together on the dimension.

tensor([1, 2, 3, 4, 5, 6])

In [51]:
out=torch.tril(torch.ones(5,5))
out#Creates a tree like structue. Triange Lower

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [55]:
out=torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [59]:
out=torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5))==0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [60]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [62]:
input=torch.zeros(2,3,4)
out=input.transpose(0,2) #Swap 0th with the 2nd dimension
out.shape

torch.Size([4, 3, 2])

In [63]:
tensor1=torch.tensor([1,2,3])
tensor2= torch.tensor([4,5,6])
tensor3= torch.tensor([7,8,9])

#Stack the tensors along a new dimension
stacked_tensor= torch.stack([tensor1,tensor2, tensor3])

In [65]:
stacked_tensor# We pass in the tensor that we want to stack together

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [67]:
import torch.nn as nn
sample=torch.tensor([10.,10.,10.])
linear=nn.Linear(3,3,bias=False) #sort of nn.sequential
print(linear(sample))

tensor([ -2.2413, -13.3878,  -3.8976], grad_fn=<SqueezeBackward4>)


In [68]:
import torch.nn.functional as F

tensor1=torch.tensor([1.0,2.0,3.0])

softmax_output=F.softmax(tensor1,dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [69]:
#Embedding vector- numberical representation of each word/char 

In [72]:
vocab_size=1000
embedding_dim=10

embedding=nn.Embedding(vocab_size, embedding_dim)

input_indices=torch.LongTensor([1,5,3,2,6])

embedding_output=embedding(input_indices)

print(embedding_output)

tensor([[-0.5030,  1.0033,  0.7856, -0.5810,  1.1106, -0.8790,  0.2070, -1.1565,
          0.8896,  0.4293],
        [-0.6214, -0.1807,  0.5866,  0.6909,  0.8042, -0.9167,  0.2913,  0.2205,
          0.2911,  0.5674],
        [ 0.2237, -0.6559, -0.3627,  1.4124, -0.0943,  0.7942, -0.2193,  0.2412,
         -0.6669, -0.8614],
        [ 0.3984,  2.3133,  2.1502, -0.0060,  0.0439, -0.1599, -0.4461, -1.0000,
          1.4939, -0.6844],
        [ 0.4831, -0.1318, -1.2008, -1.0453, -0.1585,  0.6951,  1.0479, -1.4007,
         -0.4563, -1.0673]], grad_fn=<EmbeddingBackward0>)


In [73]:
a=torch.tensor([[1,2],[3,4],[5,6]])
b=torch.tensor([[7,8,9],[10,11,12]])
print("Matrix Multiplication" ,a@b) #shorthand method

Matrix Multiplication tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [74]:
torch.matmul(a,b)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [75]:
#We cannot multiply integers and floating types

In [76]:
##Logits

In [77]:
#Normalize- somethings contribution compared to the whole context.
[2,4,6]==>[0.16,0.33,0.5]


In [81]:
##View
a=torch.rand(2,3,5)
print(a)
x,y,z=a.shape
print(x,y,z)
a=a.view(x,y,z) #make that tensor again with those dimensions
print(a)
print(a.shape)

tensor([[[0.5827, 0.8429, 0.0949, 0.7545, 0.6556],
         [0.1032, 0.7959, 0.1897, 0.3449, 0.2107],
         [0.3455, 0.7518, 0.2498, 0.9202, 0.0135]],

        [[0.6278, 0.0207, 0.2346, 0.1099, 0.7150],
         [0.2666, 0.8402, 0.9125, 0.1333, 0.8288],
         [0.4813, 0.1841, 0.0934, 0.1930, 0.0627]]])
2 3 5
tensor([[[0.5827, 0.8429, 0.0949, 0.7545, 0.6556],
         [0.1032, 0.7959, 0.1897, 0.3449, 0.2107],
         [0.3455, 0.7518, 0.2498, 0.9202, 0.0135]],

        [[0.6278, 0.0207, 0.2346, 0.1099, 0.7150],
         [0.2666, 0.8402, 0.9125, 0.1333, 0.8288],
         [0.4813, 0.1841, 0.0934, 0.1930, 0.0627]]])
torch.Size([2, 3, 5])


In [82]:
x = torch.tensor([-0.05],dtype=torch.float32)
y=nn.ReLU(x)
print(y)

ReLU(inplace=True)
